// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: leaf.proto

package ivyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_GREP                     CommandType = 1
	CommandType_AWK                      CommandType = 2
	CommandType_FIND                     CommandType = 3
	CommandType_CAT                      CommandType = 4
	CommandType_READ_FILE                CommandType = 5
	CommandType_TAIL                     CommandType = 6
	CommandType_SYSTEMCTL_STATUS         CommandType = 7
	CommandType_JOURNALCTL               CommandType = 8
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "GREP",
		2: "AWK",
		3: "FIND",
		4: "CAT",
		5: "READ_FILE",
		6: "TAIL",
		7: "SYSTEMCTL_STATUS",
		8: "JOURNALCTL",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"GREP":                     1,
		"AWK":                      2,
		"FIND":                     3,
		"CAT":                      4,
		"READ_FILE":                5,
		"TAIL":                     6,
		"SYSTEMCTL_STATUS":         7,
		"JOURNALCTL":               8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_leaf_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_leaf_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{0}
}

// Sent FROM leaf TO vine.
type LeafMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LeafMessage_Heartbeat
	//	*LeafMessage_CommandOutput
	//	*LeafMessage_DirectoryChunk
	//	*LeafMessage_Registration
	Payload       isLeafMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeafMessage) Reset() {
	*x = LeafMessage{}
	mi := &file_leaf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeafMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafMessage) ProtoMessage() {}

func (x *LeafMessage) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafMessage.ProtoReflect.Descriptor instead.
func (*LeafMessage) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{0}
}

func (x *LeafMessage) GetPayload() isLeafMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LeafMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*LeafMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *LeafMessage) GetCommandOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Payload.(*LeafMessage_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return nil
}

func (x *LeafMessage) GetDirectoryChunk() *DirectoryChunk {
	if x != nil {
		if x, ok := x.Payload.(*LeafMessage_DirectoryChunk); ok {
			return x.DirectoryChunk
		}
	}
	return nil
}

func (x *LeafMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*LeafMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

type isLeafMessage_Payload interface {
	isLeafMessage_Payload()
}

type LeafMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type LeafMessage_CommandOutput struct {
	CommandOutput *CommandOutput `protobuf:"bytes,2,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type LeafMessage_DirectoryChunk struct {
	DirectoryChunk *DirectoryChunk `protobuf:"bytes,3,opt,name=directory_chunk,json=directoryChunk,proto3,oneof"`
}

type LeafMessage_Registration struct {
	Registration *Registration `protobuf:"bytes,4,opt,name=registration,proto3,oneof"`
}

func (*LeafMessage_Heartbeat) isLeafMessage_Payload() {}

func (*LeafMessage_CommandOutput) isLeafMessage_Payload() {}

func (*LeafMessage_DirectoryChunk) isLeafMessage_Payload() {}

func (*LeafMessage_Registration) isLeafMessage_Payload() {}

// Sent FROM vine TO leaf.
type VineCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VineCommand_ExecuteCommand
	//	*VineCommand_SyncDirectory
	Payload       isVineCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VineCommand) Reset() {
	*x = VineCommand{}
	mi := &file_leaf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VineCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VineCommand) ProtoMessage() {}

func (x *VineCommand) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VineCommand.ProtoReflect.Descriptor instead.
func (*VineCommand) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{1}
}

func (x *VineCommand) GetPayload() isVineCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VineCommand) GetExecuteCommand() *ExecuteCommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*VineCommand_ExecuteCommand); ok {
			return x.ExecuteCommand
		}
	}
	return nil
}

func (x *VineCommand) GetSyncDirectory() *SyncDirectoryRequest {
	if x != nil {
		if x, ok := x.Payload.(*VineCommand_SyncDirectory); ok {
			return x.SyncDirectory
		}
	}
	return nil
}

type isVineCommand_Payload interface {
	isVineCommand_Payload()
}

type VineCommand_ExecuteCommand struct {
	ExecuteCommand *ExecuteCommandRequest `protobuf:"bytes,1,opt,name=execute_command,json=executeCommand,proto3,oneof"`
}

type VineCommand_SyncDirectory struct {
	SyncDirectory *SyncDirectoryRequest `protobuf:"bytes,2,opt,name=sync_directory,json=syncDirectory,proto3,oneof"`
}

func (*VineCommand_ExecuteCommand) isVineCommand_Payload() {}

func (*VineCommand_SyncDirectory) isVineCommand_Payload() {}

type Registration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HostId             string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // unique identifier for this parser host
	Hostname           string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AllowedDirectories []string               `protobuf:"bytes,3,rep,name=allowed_directories,json=allowedDirectories,proto3" json:"allowed_directories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_leaf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{2}
}

func (x *Registration) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Registration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Registration) GetAllowedDirectories() []string {
	if x != nil {
		return x.AllowedDirectories
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_leaf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ExecuteCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Command        CommandType            `protobuf:"varint,2,opt,name=command,proto3,enum=ivy.v1.CommandType" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"` // must be within allowed directories
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_leaf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *ExecuteCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Timeout       bool                   `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_leaf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteCommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // matches ExecuteCommandRequest.request_id
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Timeout       bool                   `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_leaf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{6}
}

func (x *CommandOutput) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandOutput) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandOutput) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandOutput) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

type SyncDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Directory     string                 `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"` // must be within allowed directories
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDirectoryRequest) Reset() {
	*x = SyncDirectoryRequest{}
	mi := &file_leaf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDirectoryRequest) ProtoMessage() {}

func (x *SyncDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDirectoryRequest.ProtoReflect.Descriptor instead.
func (*SyncDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{7}
}

func (x *SyncDirectoryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncDirectoryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type SyncDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	TarData       []byte                 `protobuf:"bytes,3,opt,name=tar_data,json=tarData,proto3" json:"tar_data,omitempty"` // tar archive of the directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDirectoryResponse) Reset() {
	*x = SyncDirectoryResponse{}
	mi := &file_leaf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDirectoryResponse) ProtoMessage() {}

func (x *SyncDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDirectoryResponse.ProtoReflect.Descriptor instead.
func (*SyncDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{8}
}

func (x *SyncDirectoryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncDirectoryResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SyncDirectoryResponse) GetTarData() []byte {
	if x != nil {
		return x.TarData
	}
	return nil
}

type DirectoryChunk struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*DirectoryChunk_FileInfo
	//	*DirectoryChunk_Chunk
	//	*DirectoryChunk_Done
	Data          isDirectoryChunk_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryChunk) Reset() {
	*x = DirectoryChunk{}
	mi := &file_leaf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryChunk) ProtoMessage() {}

func (x *DirectoryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryChunk.ProtoReflect.Descriptor instead.
func (*DirectoryChunk) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{9}
}

func (x *DirectoryChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DirectoryChunk) GetData() isDirectoryChunk_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DirectoryChunk) GetFileInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Data.(*DirectoryChunk_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

func (x *DirectoryChunk) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*DirectoryChunk_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DirectoryChunk) GetDone() bool {
	if x != nil {
		if x, ok := x.Data.(*DirectoryChunk_Done); ok {
			return x.Done
		}
	}
	return false
}

type isDirectoryChunk_Data interface {
	isDirectoryChunk_Data()
}

type DirectoryChunk_FileInfo struct {
	FileInfo *FileInfo `protobuf:"bytes,2,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

type DirectoryChunk_Chunk struct {
	Chunk []byte `protobuf:"bytes,3,opt,name=chunk,proto3,oneof"` // chunk of tar data
}

type DirectoryChunk_Done struct {
	Done bool `protobuf:"varint,4,opt,name=done,proto3,oneof"` // signals end of transfer
}

func (*DirectoryChunk_FileInfo) isDirectoryChunk_Data() {}

func (*DirectoryChunk_Chunk) isDirectoryChunk_Data() {}

func (*DirectoryChunk_Done) isDirectoryChunk_Data() {}

type FileInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size           int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,3,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_leaf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{10}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

var File_leaf_proto protoreflect.FileDescriptor

const file_leaf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"leaf.proto\x12\x06ivy.v1\"\x8a\x02\n" +
	"\vLeafMessage\x121\n" +
	"\theartbeat\x18\x01 \x01(\v2\x11.ivy.v1.HeartbeatH\x00R\theartbeat\x12>\n" +
	"\x0ecommand_output\x18\x02 \x01(\v2\x15.ivy.v1.CommandOutputH\x00R\rcommandOutput\x12A\n" +
	"\x0fdirectory_chunk\x18\x03 \x01(\v2\x16.ivy.v1.DirectoryChunkH\x00R\x0edirectoryChunk\x12:\n" +
	"\fregistration\x18\x04 \x01(\v2\x14.ivy.v1.RegistrationH\x00R\fregistrationB\t\n" +
	"\apayload\"\xa9\x01\n" +
	"\vVineCommand\x12H\n" +
	"\x0fexecute_command\x18\x01 \x01(\v2\x1d.ivy.v1.ExecuteCommandRequestH\x00R\x0eexecuteCommand\x12E\n" +
	"\x0esync_directory\x18\x02 \x01(\v2\x1c.ivy.v1.SyncDirectoryRequestH\x00R\rsyncDirectoryB\t\n" +
	"\apayload\"t\n" +
	"\fRegistration\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12/\n" +
	"\x13allowed_directories\x18\x03 \x03(\tR\x12allowedDirectories\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\xc3\x01\n" +
	"\x15ExecuteCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\acommand\x18\x02 \x01(\x0e2\x13.ivy.v1.CommandTypeR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"\x9e\x01\n" +
	"\x16ExecuteCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\bR\atimeout\"\x95\x01\n" +
	"\rCommandOutput\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\bR\atimeout\"S\n" +
	"\x14SyncDirectoryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tdirectory\x18\x02 \x01(\tR\tdirectory\"y\n" +
	"\x15SyncDirectoryResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12&\n" +
	"\x05files\x18\x02 \x03(\v2\x10.ivy.v1.FileInfoR\x05files\x12\x19\n" +
	"\btar_data\x18\x03 \x01(\fR\atarData\"\x96\x01\n" +
	"\x0eDirectoryChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\tfile_info\x18\x02 \x01(\v2\x10.ivy.v1.FileInfoH\x00R\bfileInfo\x12\x16\n" +
	"\x05chunk\x18\x03 \x01(\fH\x00R\x05chunk\x12\x14\n" +
	"\x04done\x18\x04 \x01(\bH\x00R\x04doneB\x06\n" +
	"\x04data\"[\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12'\n" +
	"\x0fchecksum_sha256\x18\x03 \x01(\tR\x0echecksumSha256*\x90\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04GREP\x10\x01\x12\a\n" +
	"\x03AWK\x10\x02\x12\b\n" +
	"\x04FIND\x10\x03\x12\a\n" +
	"\x03CAT\x10\x04\x12\r\n" +
	"\tREAD_FILE\x10\x05\x12\b\n" +
	"\x04TAIL\x10\x06\x12\x14\n" +
	"\x10SYSTEMCTL_STATUS\x10\a\x12\x0e\n" +
	"\n" +
	"JOURNALCTL\x10\b2\xe5\x01\n" +
	"\vLeafService\x127\n" +
	"\aConnect\x12\x13.ivy.v1.LeafMessage\x1a\x13.ivy.v1.VineCommand(\x010\x01\x12O\n" +
	"\x0eExecuteCommand\x12\x1d.ivy.v1.ExecuteCommandRequest\x1a\x1e.ivy.v1.ExecuteCommandResponse\x12L\n" +
	"\rSyncDirectory\x12\x1c.ivy.v1.SyncDirectoryRequest\x1a\x1d.ivy.v1.SyncDirectoryResponseB~\n" +
	"\n" +
	"com.ivy.v1B\tLeafProtoP\x01Z,github.com/aspectrr/ivy/internal/ivyv1;ivyv1\xa2\x02\x03IXX\xaa\x02\x06Ivy.V1\xca\x02\x06Ivy\\V1\xe2\x02\x12Ivy\\V1\\GPBMetadata\xea\x02\aIvy::V1b\x06proto3"

var (
	file_leaf_proto_rawDescOnce sync.Once
	file_leaf_proto_rawDescData []byte
)

func file_leaf_proto_rawDescGZIP() []byte {
	file_leaf_proto_rawDescOnce.Do(func() {
		file_leaf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaf_proto_rawDesc), len(file_leaf_proto_rawDesc)))
	})
	return file_leaf_proto_rawDescData
}

var file_leaf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_leaf_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_leaf_proto_goTypes = []any{
	(CommandType)(0),               // 0: ivy.v1.CommandType
	(*LeafMessage)(nil),            // 1: ivy.v1.LeafMessage
	(*VineCommand)(nil),            // 2: ivy.v1.VineCommand
	(*Registration)(nil),           // 3: ivy.v1.Registration
	(*Heartbeat)(nil),              // 4: ivy.v1.Heartbeat
	(*ExecuteCommandRequest)(nil),  // 5: ivy.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil), // 6: ivy.v1.ExecuteCommandResponse
	(*CommandOutput)(nil),          // 7: ivy.v1.CommandOutput
	(*SyncDirectoryRequest)(nil),   // 8: ivy.v1.SyncDirectoryRequest
	(*SyncDirectoryResponse)(nil),  // 9: ivy.v1.SyncDirectoryResponse
	(*DirectoryChunk)(nil),         // 10: ivy.v1.DirectoryChunk
	(*FileInfo)(nil),               // 11: ivy.v1.FileInfo
}
var file_leaf_proto_depIdxs = []int32{
	4,  // 0: ivy.v1.LeafMessage.heartbeat:type_name -> ivy.v1.Heartbeat
	7,  // 1: ivy.v1.LeafMessage.command_output:type_name -> ivy.v1.CommandOutput
	10, // 2: ivy.v1.LeafMessage.directory_chunk:type_name -> ivy.v1.DirectoryChunk
	3,  // 3: ivy.v1.LeafMessage.registration:type_name -> ivy.v1.Registration
	5,  // 4: ivy.v1.VineCommand.execute_command:type_name -> ivy.v1.ExecuteCommandRequest
	8,  // 5: ivy.v1.VineCommand.sync_directory:type_name -> ivy.v1.SyncDirectoryRequest
	0,  // 6: ivy.v1.ExecuteCommandRequest.command:type_name -> ivy.v1.CommandType
	11, // 7: ivy.v1.SyncDirectoryResponse.files:type_name -> ivy.v1.FileInfo
	11, // 8: ivy.v1.DirectoryChunk.file_info:type_name -> ivy.v1.FileInfo
	1,  // 9: ivy.v1.LeafService.Connect:input_type -> ivy.v1.LeafMessage
	5,  // 10: ivy.v1.LeafService.ExecuteCommand:input_type -> ivy.v1.ExecuteCommandRequest
	8,  // 11: ivy.v1.LeafService.SyncDirectory:input_type -> ivy.v1.SyncDirectoryRequest
	2,  // 12: ivy.v1.LeafService.Connect:output_type -> ivy.v1.VineCommand
	6,  // 13: ivy.v1.LeafService.ExecuteCommand:output_type -> ivy.v1.ExecuteCommandResponse
	9,  // 14: ivy.v1.LeafService.SyncDirectory:output_type -> ivy.v1.SyncDirectoryResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_leaf_proto_init() }
func file_leaf_proto_init() {
	if File_leaf_proto != nil {
		return
	}
	file_leaf_proto_msgTypes[0].OneofWrappers = []any{
		(*LeafMessage_Heartbeat)(nil),
		(*LeafMessage_CommandOutput)(nil),
		(*LeafMessage_DirectoryChunk)(nil),
		(*LeafMessage_Registration)(nil),
	}
	file_leaf_proto_msgTypes[1].OneofWrappers = []any{
		(*VineCommand_ExecuteCommand)(nil),
		(*VineCommand_SyncDirectory)(nil),
	}
	file_leaf_proto_msgTypes[9].OneofWrappers = []any{
		(*DirectoryChunk_FileInfo)(nil),
		(*DirectoryChunk_Chunk)(nil),
		(*DirectoryChunk_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaf_proto_rawDesc), len(file_leaf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_proto_depIdxs,
		EnumInfos:         file_leaf_proto_enumTypes,
		MessageInfos:      file_leaf_proto_msgTypes,
	}.Build()
	File_leaf_proto = out.File
	file_leaf_proto_goTypes = nil
	file_leaf_proto_depIdxs = nil
}
