// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: leaf.proto

package ivyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeafService_Connect_FullMethodName        = "/ivy.v1.LeafService/Connect"
	LeafService_ExecuteCommand_FullMethodName = "/ivy.v1.LeafService/ExecuteCommand"
	LeafService_SyncDirectory_FullMethodName  = "/ivy.v1.LeafService/SyncDirectory"
)

// LeafServiceClient is the client API for LeafService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeafServiceClient interface {
	// Bidirectional stream: leaf connects and keeps the stream alive.
	// The vine sends commands through the stream; the leaf responds
	// with output, heartbeats, and directory sync data.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeafMessage, VineCommand], error)
	// Unary fallback: execute a single command on the parser host.
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// Unary: trigger a directory sync from the parser host.
	SyncDirectory(ctx context.Context, in *SyncDirectoryRequest, opts ...grpc.CallOption) (*SyncDirectoryResponse, error)
}

type leafServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeafServiceClient(cc grpc.ClientConnInterface) LeafServiceClient {
	return &leafServiceClient{cc}
}

func (c *leafServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeafMessage, VineCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeafService_ServiceDesc.Streams[0], LeafService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LeafMessage, VineCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeafService_ConnectClient = grpc.BidiStreamingClient[LeafMessage, VineCommand]

func (c *leafServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, LeafService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leafServiceClient) SyncDirectory(ctx context.Context, in *SyncDirectoryRequest, opts ...grpc.CallOption) (*SyncDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDirectoryResponse)
	err := c.cc.Invoke(ctx, LeafService_SyncDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeafServiceServer is the server API for LeafService service.
// All implementations must embed UnimplementedLeafServiceServer
// for forward compatibility.
type LeafServiceServer interface {
	// Bidirectional stream: leaf connects and keeps the stream alive.
	// The vine sends commands through the stream; the leaf responds
	// with output, heartbeats, and directory sync data.
	Connect(grpc.BidiStreamingServer[LeafMessage, VineCommand]) error
	// Unary fallback: execute a single command on the parser host.
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// Unary: trigger a directory sync from the parser host.
	SyncDirectory(context.Context, *SyncDirectoryRequest) (*SyncDirectoryResponse, error)
	mustEmbedUnimplementedLeafServiceServer()
}

// UnimplementedLeafServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeafServiceServer struct{}

func (UnimplementedLeafServiceServer) Connect(grpc.BidiStreamingServer[LeafMessage, VineCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedLeafServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedLeafServiceServer) SyncDirectory(context.Context, *SyncDirectoryRequest) (*SyncDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncDirectory not implemented")
}
func (UnimplementedLeafServiceServer) mustEmbedUnimplementedLeafServiceServer() {}
func (UnimplementedLeafServiceServer) testEmbeddedByValue()                     {}

// UnsafeLeafServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeafServiceServer will
// result in compilation errors.
type UnsafeLeafServiceServer interface {
	mustEmbedUnimplementedLeafServiceServer()
}

func RegisterLeafServiceServer(s grpc.ServiceRegistrar, srv LeafServiceServer) {
	// If the following call panics, it indicates UnimplementedLeafServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeafService_ServiceDesc, srv)
}

func _LeafService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LeafServiceServer).Connect(&grpc.GenericServerStream[LeafMessage, VineCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeafService_ConnectServer = grpc.BidiStreamingServer[LeafMessage, VineCommand]

func _LeafService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeafService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeafService_SyncDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafServiceServer).SyncDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeafService_SyncDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafServiceServer).SyncDirectory(ctx, req.(*SyncDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeafService_ServiceDesc is the grpc.ServiceDesc for LeafService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeafService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ivy.v1.LeafService",
	HandlerType: (*LeafServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _LeafService_ExecuteCommand_Handler,
		},
		{
			MethodName: "SyncDirectory",
			Handler:    _LeafService_SyncDirectory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _LeafService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "leaf.proto",
}
